-- 003_recommendations.sql
--
-- Phase 6: per-campaign live-performance recommendations + a place to stash
-- the generated replacement-angle brief when the recommendation is "replace".
--
-- Apply with:
--   psql "$DATABASE_URL" -f scripts/sql/003_recommendations.sql
--
-- Idempotent.

-- ── enums ────────────────────────────────────────────────────────────────────

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'recommendation_classification') THEN
        CREATE TYPE recommendation_classification AS ENUM (
            'working',           -- above baseline, keep running
            'underperforming',   -- below baseline; recommend pause + replace
            'failing',           -- zero conversions after meaningful spend; pause hard
            'insufficient_data'  -- not enough spend/impressions to judge yet
        );
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'recommendation_action') THEN
        CREATE TYPE recommendation_action AS ENUM (
            'keep',
            'pause',
            'replace'
        );
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'recommendation_decision') THEN
        CREATE TYPE recommendation_decision AS ENUM (
            'pending',
            'accepted',
            'rejected'
        );
    END IF;
END $$;


-- ── replacement_briefs ───────────────────────────────────────────────────────
--
-- Generated by the replacement-angle generator when a recommendation = replace.
-- Optional — for the MVP we can leave this table empty and just render the
-- recommendation without a pre-generated brief; the angle generator lands later.

CREATE TABLE IF NOT EXISTS replacement_briefs (
    id                  BIGSERIAL    PRIMARY KEY,
    ramp_id             TEXT         NOT NULL,
    source_campaign_urn TEXT         NOT NULL,      -- the campaign being replaced
    cohort_id           TEXT,                       -- carried over from the source campaign
    cohort_signature    TEXT,
    channel             TEXT,
    angle               TEXT,
    angle_label         TEXT,
    headline            TEXT,
    subheadline         TEXT,
    photo_subject       TEXT,
    rationale           TEXT,
    generator_notes     TEXT,                       -- free-form context from the generator
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS replacement_briefs_ramp_idx
    ON replacement_briefs (ramp_id, source_campaign_urn);


-- ── ramp_recommendations ─────────────────────────────────────────────────────
--
-- One row per evaluated campaign per evaluation run. UNIQUE on
-- (ramp_id, campaign_urn) so each subsequent evaluation overwrites the
-- previous recommendation (we don't keep history; the audit log captures
-- intent).

CREATE TABLE IF NOT EXISTS ramp_recommendations (
    id                    BIGSERIAL    PRIMARY KEY,
    ramp_id               TEXT         NOT NULL,
    campaign_urn          TEXT         NOT NULL,
    cohort_signature      TEXT,
    channel               TEXT,
    angle                 TEXT,
    classification        recommendation_classification NOT NULL,
    action                recommendation_action          NOT NULL,
    rationale             TEXT,                              -- 1-2 sentences explaining the call
    metric_signal         JSONB        NOT NULL DEFAULT '{}'::jsonb,  -- {ctr, cpa, spend, clicks, impressions}
    replacement_brief_id  BIGINT       REFERENCES replacement_briefs(id) ON DELETE SET NULL,
    decision              recommendation_decision  NOT NULL DEFAULT 'pending',
    decided_by            TEXT,
    decided_at            TIMESTAMPTZ,
    generated_at          TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    UNIQUE (ramp_id, campaign_urn)
);

CREATE INDEX IF NOT EXISTS ramp_recommendations_ramp_decision_idx
    ON ramp_recommendations (ramp_id, decision);
